#!/usr/bin/env node

	// DO NOT MODIFY.
	// This file is automatically generated by bat2js.
	// To modify the contents, edit the original .bat file and run bat2js again.
	// Compiled from: hello.bat

	const fs = require('fs');
	const path = require('path');
	const { spawn } = require('child_process');

	// -- START COMPILED CODE --

	let hi = `Hello`;
let world = `world!`;
console.log(`${hi} ${world}`);
console.log(`Goodbye world!`);
setTimeout(() => {}, 3000);
process.exit(0);
